name: CI fashion-tv

on:
  push:
    branches:
      - master
      - develop
      - feature/*

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Execute tests via PHPUnit
        run: vendor/bin/phpunit --exclude-group=incomplete
