name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
      - name: Run tests
        run: |
          echo Running  tests
          ./vendor/bin/phpunit tests/Feature/ApiTest.php --testdox
